/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lifemetric;

/**
 *IdealBedTimeGUI.java
 *@author Murilo Carlos Batiuk
 * November 9th 2024 
 */
public class IdealBedTimeGUI extends javax.swing.JFrame {

    private int wakeUpTime;
    private int bedTime;

    /**
     * Creates new form IdealBedTimeGUI
     */
    public IdealBedTimeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        idealbedtimeLBL = new javax.swing.JLabel();
        ibttext1LBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ibttext2LBL = new javax.swing.JLabel();
        ibtquestionLBL = new javax.swing.JLabel();
        ibtquestionTF = new javax.swing.JTextField();
        ibtreturnBTN = new javax.swing.JButton();
        ibtmainpageBTN = new javax.swing.JButton();
        ibtcalculateBTN = new javax.swing.JButton();
        ibtageLBL = new javax.swing.JLabel();
        ibtageTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ibddisplayTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 167, 186));

        idealbedtimeLBL.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        idealbedtimeLBL.setText("Ideal Bed Time");

        ibttext1LBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ibttext1LBL.setText("According to your age and gender, you require a different amount of sleep.");

        ibttext2LBL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ibttext2LBL.setText("Check what time is your ideal time to go to bed to have a good night of sleep. ");

        ibtquestionLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtquestionLBL.setText("What time do you need to wake up?");

        ibtreturnBTN.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtreturnBTN.setText("RETURN TO SLEEP TRACKER PAGE");
        ibtreturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibtreturnBTNActionPerformed(evt);
            }
        });

        ibtmainpageBTN.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtmainpageBTN.setText("RETURN  TO MAIN PAGE");
        ibtmainpageBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibtmainpageBTNActionPerformed(evt);
            }
        });

        ibtcalculateBTN.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ibtcalculateBTN.setText("CALCULATE!");
        ibtcalculateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibtcalculateBTNActionPerformed(evt);
            }
        });

        ibtageLBL.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        ibtageLBL.setText("Age:");

        ibtageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibtageTFActionPerformed(evt);
            }
        });

        ibddisplayTA.setColumns(20);
        ibddisplayTA.setRows(5);
        jScrollPane1.setViewportView(ibddisplayTA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(ibtquestionLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ibtquestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(ibtageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ibtageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ibtreturnBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ibtmainpageBTN))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(ibtcalculateBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ibttext1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(67, 67, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(idealbedtimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(ibttext2LBL, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibtquestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibtquestionLBL)
                    .addComponent(ibtageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibtageLBL))
                .addGap(67, 67, 67)
                .addComponent(ibtcalculateBTN)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibtmainpageBTN)
                    .addComponent(ibtreturnBTN))
                .addGap(13, 13, 13))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idealbedtimeLBL)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ibttext1LBL)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ibttext2LBL)
                    .addGap(12, 12, 12)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ibtreturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibtreturnBTNActionPerformed
        // TODO add your handling code here:
        SleepTrackerMainPageGUI stmp = new SleepTrackerMainPageGUI();
        stmp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ibtreturnBTNActionPerformed

    private void ibtmainpageBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibtmainpageBTNActionPerformed
        MainAppGUI main = new MainAppGUI();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_ibtmainpageBTNActionPerformed

    private void ibtcalculateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibtcalculateBTNActionPerformed
        // TODO add your handling code here:
        
        
        int age = Integer.parseInt(ibtageTF.getText());
        IdealBedTime tempIBT = new IdealBedTime(age);
        tempIBT.setWakeUpTime(wakeUpTime);
        tempIBT.setBedTime(bedTime);
        tempIBT.wakeUpAt();
        
        ibddisplayTA.setText(tempIBT.getMessage());
        
    }//GEN-LAST:event_ibtcalculateBTNActionPerformed

    private void ibtageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibtageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibtageTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealBedTimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealBedTimeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea ibddisplayTA;
    private javax.swing.JLabel ibtageLBL;
    private javax.swing.JTextField ibtageTF;
    private javax.swing.JButton ibtcalculateBTN;
    private javax.swing.JButton ibtmainpageBTN;
    private javax.swing.JLabel ibtquestionLBL;
    private javax.swing.JTextField ibtquestionTF;
    private javax.swing.JButton ibtreturnBTN;
    private javax.swing.JLabel ibttext1LBL;
    private javax.swing.JLabel ibttext2LBL;
    private javax.swing.JLabel idealbedtimeLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
